In [1]:
import torch

$y=3x^{3}$

In [2]:
x=torch.tensor([2],dtype=torch.float32,requires_grad=True)

In [3]:
y=3*x**3

In [4]:
y.backward()

In [6]:
x.grad

tensor([36.])

In [24]:
x1=torch.tensor([4],dtype=torch.float32,requires_grad=True)
x2=torch.tensor([2],dtype=torch.float32,requires_grad=True)

In [25]:
y=2*x1**2+3*x2**3

In [26]:
y.backward()

In [27]:
x1.grad

tensor([16.])

In [28]:
x2.grad

tensor([36.])